services:
  - postgresql
sudo: false
cache: bundler
language: ruby
rvm:
  - "2.4.1"
matrix:
  include:
    - rvm: 2.2.5
      env:
        - ACTION_CABLE_ALLOWED_REQUEST_ORIGINS=https://mysweetbestsite.com
        - LOG_LEVEL=debug
        - SECRET_TOKEN=YOYOYOYOYYOYOYOYOYO

